---
title: "C28105 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28105"
helpviewer_keywords: 
  - "C28105"
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 3
---
# C28105
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Avviso C28105: Risorsa con perdita di memoria a causa di un'eccezione  
  
 La risorsa specificata non viene liberata quando viene generata un'eccezione.  L'istruzione specificata dal percorso può generare un'eccezione.  Questo avviso è simile all'avviso [C28103](../code-quality/c28103.md), ma in questo caso un'eccezione è coinvolta.  
  
## Esempio  
 Il seguente codice di esempio genera questo warning:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 L'esempio di codice seguente evita questo avviso:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```